---
- name: Instalar Nginx
  hosts: dev
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: holamundo

  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copiar sitio web
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Aplicar config de Nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Reiniciar Nginx

    - name: Habilitar sitio nuevo
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Reiniciar Nginx

  handlers:
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
